"""PDF generation for the Directory Versions module. Pure function: given a
DirectoryVersion (unsaved is fine) and a snapshot dict from
services.directory_version_service.build_directory_snapshot(), returns raw
PDF bytes. No DB writes, no disk writes -- the caller decides where the
bytes go.
"""

import io

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import (
    BaseDocTemplate, Frame, PageBreak, PageTemplate, Paragraph, Spacer,
    Table, TableStyle,
)
from reportlab.platypus.tableofcontents import TableOfContents

from utils.logger import get_logger

logger = get_logger(__name__)

BRAND_NAVY = colors.HexColor("#1a3a6b")
FOOTER_TEXT = "Generated from WR Telephone Directory Management System"

_HEADER_ROW_STYLE = TableStyle([
    ("BACKGROUND", (0, 0), (-1, 0), BRAND_NAVY),
    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
    ("FONTSIZE", (0, 0), (-1, -1), 8),
    ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f2f4f8")]),
])


class _VersionDocTemplate(BaseDocTemplate):
    """Bookmarks every Heading1/Heading2 paragraph so the cover-page Table
    of Contents can resolve real page numbers -- reportlab's documented
    2-pass TOC recipe (see generate_pdf's doc.multiBuild call)."""

    def afterFlowable(self, flowable):
        if isinstance(flowable, Paragraph) and flowable.style.name in ("Heading1", "Heading2"):
            level = 0 if flowable.style.name == "Heading1" else 1
            key = f"h-{id(flowable)}"
            self.canv.bookmarkPage(key)
            self.notify("TOCEntry", (level, flowable.getPlainText(), self.page, key))


def _footer(canvas_, doc_):
    canvas_.saveState()
    canvas_.setFont("Helvetica", 8)
    canvas_.setFillColor(colors.grey)
    canvas_.drawCentredString(A4[0] / 2, 1.2 * cm, FOOTER_TEXT)
    canvas_.drawRightString(A4[0] - 1.8 * cm, 1.2 * cm, f"Page {canvas_.getPageNumber()}")
    canvas_.restoreState()


def _styles():
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(
        "CoverTitle", parent=styles["Title"], textColor=BRAND_NAVY, fontSize=22, spaceAfter=6,
    ))
    styles.add(ParagraphStyle(
        "CoverMeta", parent=styles["Normal"], fontSize=12, leading=18, alignment=1,
    ))
    return styles


def _cover_page(version, styles):
    return [
        Spacer(1, 5 * cm),
        Paragraph("Western Region Telephone Directory", styles["CoverTitle"]),
        Spacer(1, 0.5 * cm),
        Paragraph(version.version_name, styles["CoverMeta"]),
        Paragraph(f"Version {version.version_number}", styles["CoverMeta"]),
        Paragraph(f"{_month_name(version.month)} {version.year}", styles["CoverMeta"]),
        Spacer(1, 1 * cm),
        Paragraph(
            f"Generated on {version.generated_on.strftime('%d-%b-%Y %H:%M') if version.generated_on else '-'}",
            styles["CoverMeta"],
        ),
        Paragraph(
            f"Generated by {version.generated_by_user.username if version.generated_by_user else 'System'}",
            styles["CoverMeta"],
        ),
    ]


_MONTH_NAMES = [
    "", "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December",
]


def _month_name(month):
    return _MONTH_NAMES[month] if 1 <= month <= 12 else str(month)


def _section_table(headers, rows, col_widths=None):
    data = [headers] + rows
    table = Table(data, colWidths=col_widths, repeatRows=1)
    table.setStyle(_HEADER_ROW_STYLE)
    return table


def _employee_row(emp):
    return [
        emp.employee_name or "-",
        emp.designation or "-",
        emp.office_phone or "-",
        emp.mobile_phone or "-",
        emp.email or "-",
    ]


def _org_section(org_name, data, styles):
    story = [Paragraph(org_name, styles["Heading1"])]
    if data.get("address"):
        story.append(Paragraph(data["address"], styles["Normal"]))
    story.append(Spacer(1, 0.2 * cm))

    if data["employees"]:
        rows = [_employee_row(e) for e in data["employees"]]
        story.append(_section_table(
            ["Name", "Designation", "Office", "Mobile", "Email"], rows,
            col_widths=[4 * cm, 4 * cm, 3 * cm, 3 * cm, 4.5 * cm],
        ))
        story.append(Spacer(1, 0.3 * cm))

    for label, key in (("Control Rooms", "control_rooms"), ("Switchyards", "switchyards")):
        if data[key]:
            rows = [[n.name or "-", n.phone_number or "-", n.email or "-"] for n in data[key]]
            story.append(Paragraph(label, styles["Heading2"]))
            story.append(_section_table(
                ["Name", "Phone", "Email"], rows,
                col_widths=[6 * cm, 4 * cm, 8.5 * cm],
            ))
            story.append(Spacer(1, 0.3 * cm))

    story.append(Spacer(1, 0.4 * cm))
    return story


def _role_section(title, heads, styles):
    if not heads:
        return []
    story = [Paragraph(title, styles["Heading2"])]
    rows = [
        [
            h.resolved_name or "-",
            getattr(h, "role_title", None) or getattr(h, "designation", None) or "-",
            h.organization.organization_name if h.organization else "-",
            h.resolved_mobile_phone or "-",
            h.resolved_email or "-",
        ]
        for h in heads
    ]
    story.append(_section_table(
        ["Name", "Designation", "Organization", "Mobile", "Email"], rows,
        col_widths=[3.5 * cm, 3.5 * cm, 3.5 * cm, 2.5 * cm, 5.5 * cm],
    ))
    story.append(Spacer(1, 0.4 * cm))
    return story


def _employees_section(title, employees, styles):
    if not employees:
        return []
    story = [Paragraph(title, styles["Heading2"])]
    rows = [_employee_row(e) for e in employees]
    story.append(_section_table(
        ["Name", "Designation", "Office", "Mobile", "Email"], rows,
        col_widths=[4 * cm, 4 * cm, 3 * cm, 3 * cm, 4.5 * cm],
    ))
    story.append(Spacer(1, 0.4 * cm))
    return story


def _numbers_section(title, numbers, styles):
    if not numbers:
        return []
    story = [Paragraph(title, styles["Heading2"])]
    rows = [[n.organization or "-", n.name or "-", n.phone_number or "-", n.email or "-"] for n in numbers]
    story.append(_section_table(
        ["Organization", "Name", "Phone", "Email"], rows,
        col_widths=[4.5 * cm, 4.5 * cm, 3 * cm, 4.5 * cm],
    ))
    story.append(Spacer(1, 0.4 * cm))
    return story


def _emergency_section(contacts, styles):
    if not contacts:
        return []
    story = [Paragraph("Emergency Contacts", styles["Heading2"])]
    rows = [
        [
            c.employee.employee_name if c.employee else "-",
            c.contact_name or "-", c.relation or "-", c.phone or "-",
        ]
        for c in contacts
    ]
    story.append(_section_table(
        ["Employee", "Contact Name", "Relation", "Phone"], rows,
        col_widths=[4.5 * cm, 4.5 * cm, 3 * cm, 4.5 * cm],
    ))
    story.append(Spacer(1, 0.4 * cm))
    return story


def generate_pdf(version, snapshot):
    """Returns raw PDF bytes for `version` (a DirectoryVersion, saved or
    not) using `snapshot` (see build_directory_snapshot)."""
    buf = io.BytesIO()
    doc = _VersionDocTemplate(
        buf, pagesize=A4, topMargin=2 * cm, bottomMargin=2 * cm,
        leftMargin=1.8 * cm, rightMargin=1.8 * cm,
    )
    frame = Frame(doc.leftMargin, doc.bottomMargin, doc.width, doc.height, id="main")
    doc.addPageTemplates([PageTemplate(id="main", frames=[frame], onPage=_footer)])

    styles = _styles()

    story = []
    story += _cover_page(version, styles)
    story.append(PageBreak())

    story.append(Paragraph("Table of Contents", styles["Heading1"]))
    toc = TableOfContents()
    toc.levelStyles = [
        ParagraphStyle(name="TOC0", fontSize=12, leftIndent=0, leading=16),
        ParagraphStyle(name="TOC1", fontSize=10, leftIndent=12, leading=13),
    ]
    story.append(toc)
    story.append(PageBreak())

    for org_name, data in snapshot["grouped"].items():
        story += _org_section(org_name, data, styles)

    story += _employees_section("Utility Heads", snapshot["utility_heads"], styles)
    story += _role_section("Administrative Heads", snapshot["administrative_heads"], styles)
    story += _employees_section("Key Managerial Personnel (KMP)", snapshot["kmp"], styles)
    story += _employees_section("Employees", [
        e for org in snapshot["grouped"].values() for e in org["employees"]
    ], styles)
    story += _numbers_section("Control Rooms", [
        n for org in snapshot["grouped"].values() for n in org["control_rooms"]
    ], styles)
    story += _numbers_section("Switchyards", [
        n for org in snapshot["grouped"].values() for n in org["switchyards"]
    ], styles)
    story += _emergency_section(snapshot["emergency_contacts"], styles)

    doc.multiBuild(story)
    return buf.getvalue()
